services:
  pulsemation:
    container_name: pulsemation
    build:
      context: .
      args:
        VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
        VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
        VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
        VITE_WEBHOOK_URL: ${VITE_WEBHOOK_URL}
    image: pulsemation-app:latest
    ports:
      - "8081:80"
    env_file:
      - .env
